### ISSUE TITLE
Empty URLs after import/sync

### ISSUE THREAD

**Issue by pchalasani** [hkgnp/logseq-readwise-plugin#11]
Hi after importing I see entries like this:

```
And I have to add that Medium platform is bad for write, the editor is too much simple that became very complicate to use, for example there’re a lot of shortcust to insert Mardown sintax but they’re not the standard Mardown shortcuts, are not well
              link:: [null](null)
              on:: [[Jan 23rd, 2022]]
              tags::
```

Note the `link:: [null](null)`
I was expecting it would contain the link to the article.
Any ideas? Thanks for this great tool

**Comment by benjypng** [comment]
Hi!
Can I confirm which integration is this? Instapaper or?

**Comment by pchalasani** [comment]
It's actually about highlights created in the Alfread app https://www.producthunt.com/posts/alfread

**Comment by benjypng** [comment]
I see! Hmm, I haven't used this read later app before!
In light of the new official plugin going to be released by Readwise soon,
I will not be adding new features as I think everyone will be moving to the
official one once it's out, so am working on other plugins now.
Sorry about that!

**Comment by pchalasani** [comment]
Makes sense, thanks! I didn't realize the implementation would need to be aware of where the highlights were done. I just wanted to be sure I was not doing something wrong. I will wait for the official RW + LS plugin

**Comment by benjypng** [comment]
Thanks for your kind understanding! Yes the implementation notes this as
how the imports are setup vary slightly depending on the source!
