### ISSUE TITLE
Images are too big

### ISSUE THREAD

**Issue by deklanw** [hkgnp/logseq-readwise-plugin#12]
There should be an option to specify max image height/width and then scale down the images appropriately with this syntax

`![book_image](link){:height 180, :width 120}`

**Comment by benjypng** [comment]
Thanks for the suggestion!

Readwise folks are working on an official plugin now, so I will not be prioritising Readwise feature requests at present since I think everyone will want to use the official one when it comes out.

Will update if I do work on this!

**Comment by benjypng** [comment]
Implemented in v4.0+.

**Comment by deklanw** [comment]
@hkgnp It's a nice improvement but I was thinking for content as well. Tweets with more than one image are especially bad.

**Comment by benjypng** [comment]
I see. Please update to 4.0.6. Tweet images follow the settings.
