### ISSUE TITLE
Books with no highlights abort sync

### ISSUE THREAD

**Issue by luhmann** [hkgnp/logseq-readwise-plugin#15]
Thank you for the great plugin!

When trying to use it I ran into the same issue that was reported with https://github.com/hkgnp/logseq-readwise-plugin/issues/2 and solved via this PR https://github.com/hkgnp/logseq-readwise-plugin/pull/3.

I just wanted to open a PR with the fix when I found the original issue.

The problem might be more prevalent now because the offending source in my case was the "Quick passages"-document that Readwise seems to add for all new users as an instruction manual. It does not have any highlights and when encountering it the sync freezes. As the document seems to have the date of the user signup and the newest sources are imported first, only one source was imported in my case before the import stopped. Deleting the document also does not help, because the API Responses seem to still contain ist, even though it does not show up in the UI any longer.

It looks like the fix mentioned above is not part of the source code anymore? Would you be open to add it again so that the plugin works in the mentioned case? I opened a PR that does that, but as the issue was solved before the credit should go to @MattHulse

**Comment by benjypng** [comment]
Yes I did the merge! I did a major refactor recently to accommodate customising of the highlight pages and must have forgotten to include it.

Thanks!
