### ISSUE TITLE
Does this plugin conflict with the roam research Readwise plugin?

### ISSUE THREAD

**Issue by jesper-bylund** [hkgnp/logseq-readwise-plugin#17]
Hi,
Before I activate this plugin I just want to ask if it's the same format as the Roam Readwise plugin, or will I get duplicates?

**Comment by benjypng** [comment]
Hmm, I am not sure what you mean. If you already have highlights in your Logseq graph (maybe using the Obsidian approach), then yes there will definitely be duplicates.

**Comment by jesper-bylund** [comment]
Let me be more detailed:
I've been using Readwise plugin for Roam util I switched to LogSeq. I have over a thousand notes synced. I want to avoid duplications, and it seems like it's only the document name format that is the ID for syncing. 

So does this plugin use the same format, or is it a new one?

**Comment by benjypng** [comment]
I see.
There will be duplications **unless** you manually change the last updated date in the plugin settings so that it only syncs the new highlights that have not come into your graph.

**Comment by jesper-bylund** [comment]
That's beautiful! I was not aware that that was a setting. Thank you!
