### ISSUE TITLE
The plugin stucks frequently

### ISSUE THREAD

**Issue by arqueon** [hkgnp/logseq-readwise-plugin#18]
In Step 3 when I start the sync the plugin gets stuck in x% (I'm not referring to the "Please wait for Readwise's cooling off period to lapse." message) and refuses to sync more highlights. If I manually activate "Stop Syncing", and restart de plugin it starts from the beginning and advances a little bit more, but eventually gets stuck again and I need to restart it multiple times.

**Comment by benjypng** [comment]
It is likely due to an issue with one of the highlights.
Could you let me know what appears in the developer console when the plugin gets stuck?

**Comment by afterless** [comment]
I am also having the same issue with the error: `Uncaught (in promise) TypeError: Cannot read properties of null (reading 'length')` 

During the highlights retrieval process when this error is thrown, `const currPage = await logseq.Editor.getCurrentPage()` is ran in `Sync.tsx` and currPage is equal to null, hence pageBlocksTree also returns null which is why I think the error occurs, not sure what is causing it to return null however

**Comment by afterless** [comment]
As a followup, downgrading to version 0.6.5 seems to be a temporary solution to this problem, hinting that there might have been some breaking API changes in the logseq library from 0.6.5 to 0.6.6

**Comment by benjypng** [comment]
Thanks afterless. Yes there are a few breaking changes with 0.6.6. Some previous APIs seem to have some issues working. Have reported it to the devs, and are currently awaiting their response.

**Comment by kwojtaszek** [comment]
It might be also related to twitter sync: https://share.getcloudapp.com/OAu6YAGb. See the log screenshot

**Comment by benjypng** [comment]
Could you try with v4.0.8 please?
Also, could you share the Tweet link of the ones in your screenshot?

**Comment by benjypng** [comment]
Hmm, could you try with v4.0.13?
I did some refactoring to try and catch this bug.

**Comment by arqueon** [comment]
I used 4.0.8 and now 4.0.13 and the problem is solved, no more stucking.

**Comment by kwojtaszek** [comment]
It's also solved in 4.0.13 for me. I will check it more throughout the next days to verify if there are any issues

**Comment by benjypng** [comment]
Yes, please do and keep me posted! I will close this issue for now, but please feel free to re-open it if any new issues pop up!
