### ISSUE TITLE
Duplicate data

### ISSUE THREAD

**Issue by JaneSu** [hkgnp/logseq-readwise-plugin#19]
Every time i synchronize data from readwise, there will find that duplicate blocks are created

**Comment by benjypng** [comment]
What version of Logseq are you on?
There are some issues with this plugin with Logseq 0.6.6.
Please try with Logseq 0.6.5 and see if the problem still persists.

**Comment by JaneSu** [comment]
I found this problem with 0.6.6 version, use back to 0.6.5 and it's fine!
