### ISSUE TITLE
Initial Sync Keeps Hanging, Dev Tools shows exception

### ISSUE THREAD

**Issue by MattHulse** [hkgnp/logseq-readwise-plugin#2]
My initial sync keeps hanging.  It seems to stop at the same document every time.  The last document processed appears to have been created successfully.  Unfortunately I can't tell what the next document is as it is likely the one causing trouble.  Sometimes article titles have characters that are not valid as filenames (I've noticed this in the Obsidian Readwise Export).  So maybe one of the sources has a character that is invalid for a filename and that is causing the import to stop?

The exception I see in the console is this:
```
index.ddbc8bca.js:2 Uncaught (in promise) TypeError: Cannot read properties of null (reading '$cljs$core$IFn$_invoke$arity$1$')
    at $clojure$zip$node$$ (zip.cljs:64)
    at $frontend$modules$outliner$core$get_node_tree_topmost_last_loc$$ (core.cljs:355)
    at $frontend$modules$outliner$core$insert_nodes$$ (core.cljs:377)
    at $frontend$handler$editor$paste_block_vec_tree_at_target$$ (editor.cljs:2205)
    at $frontend$handler$editor$paste_block_tree_after_target$$ (editor.cljs:2267)
    at api.cljs:430
    at k (helpers.ts:141)
    at Ae.<anonymous> (LSPlugin.core.ts:186)
    at Ae.a.emit (index.js:181)
    at B.<anonymous> (LSPlugin.caller.ts:202)
```

**Comment by benjypng** [comment]
@MattHulse If you open up Dev Tools as you are syncing, the last `Updating xxx` before the error happens will be the source that created the issue. Do you mind seeing which source it is so I can test it as well?

I've only really tested it with Kindle and Twitter integrations so it could be a use case that I have not accounted for.

Meanwhile it may be helpful to test it on a test graph so you don't need to subject your own graph through this.

Thanks again for your help in making the plugin a better one!

**Comment by MattHulse** [comment]
As it turns out, the article it keeps choking on actually exists in my readwise twice and if I scroll up in the log has already been imported once before.  This is because I'm part of the Readwise Reader beta so I have this article imported from Instapaper, but then I imported it again from readwise reader.  I will post the two different versions of this article when exported from Readwise directly into markdown.  I don't know if the problem is that there are two articles with the same name or if there is something different about the new readwise markdown export that is causing a parsing error with logseq.

Also notice the article title contains "Can't" but the markdown file exported from Readwise strips the apostrophe.  I don't know if that is causing problems.  Anyway, here you go...

**Instapaper version of highlights exported to MarkDown**
[When You and Your Spouse Cant Agree - Focus on the Family.md](https://github.com/hkgnp/logseq-readwise-plugin/files/7686838/When.You.and.Your.Spouse.Cant.Agree.-.Focus.on.the.Family.md)

**Readwise version of highlights exported to MarkDown** (notice the export automatically named this -2)
[When You and Your Spouse Cant Agree - Focus on the Family-2.md](https://github.com/hkgnp/logseq-readwise-plugin/files/7686841/When.You.and.Your.Spouse.Cant.Agree.-.Focus.on.the.Family-2.md)

**Comment by MattHulse** [comment]
I'm actually considering just deleting one of the duplicates to see if that fixes the issue, but at the same time I want to help test this if there is something that needs to be fixed in the plugin.  I will leave things alone until I hear back from you.  Thanks again @hkgnp!

**Comment by MattHulse** [comment]
The main difference I see is the location link.  That and the readwise version includes additional highlighting within the highlight text (using markdown highlight syntax)

**Comment by benjypng** [comment]
@MattHulse Thanks for sharing the attachments! 

I noticed that they are not using the format for my plugin though. Looks like they were created by Obsidian!

Could you help to attach those created by this plugin please?

Edit: I tried to replicate your issue by creating an Instapaper integration in Readwise, save the page that you indicated in your example, made some highlights in Instapaper and sync-ed them into Readwise. Then I used the plugin in Logseq to pull the highlights into Logseq. The attached is what the `.md` file should look like:

[When You and Your Spouse Can't Agree - Focus on the Family (Readwise).md](https://github.com/hkgnp/logseq-readwise-plugin/files/7689722/When.You.and.Your.Spouse.Can.t.Agree.-.Focus.on.the.Family.Readwise.md)

**Comment by MattHulse** [comment]
Hmmm, actually the instapaper version doesn't show up.  Maybe that's the one that is broken.  The one that does show up is the readwise reader version.  Here it is:

[When You and Your Spouse Can't Agree - Focus on the Family (Readwise).md](https://github.com/hkgnp/logseq-readwise-plugin/files/7690207/When.You.and.Your.Spouse.Can.t.Agree.-.Focus.on.the.Family.Readwise.md)

Now that I dig into this further, it appears there are duplicate articles both from readwise reader (maybe a bug in that app which is still early beta).

I'm just going to delete the second article and see if that gets me over this hump.

**Comment by MattHulse** [comment]
Okay that's weird.  I deleted the second article and deleted all of the readwise notes and reloaded the plugin.  However, it is still trying to add this article a second time and as soon as it does it chokes.  Maybe I'll have to wait until tomorrow in case the articles are cached on Readwise side.

**Comment by benjypng** [comment]
That's indeed interesting! Have you tried updating to version 2.4? I've added in a method to cater to scenarios where there maybe problems finding the correct block to add new highlights to.

If the issue still persists, if you don't, could you attach more of the console errors (so the part above and below the error) and I can try to make further sense of it.

Thank you!

**Comment by MattHulse** [comment]
I have been playing around with debugging the code (loaded the extension locally and built it with pretty code so I could step through it).  Very interesting stuff.

Anyway, I have been able to confirm that the book list contains this article twice.

The first time is this:
```
{
    "id": 12187883,
    "title": "When You and Your Spouse Can't Agree - Focus on the Family",
    "author": "focusonthefamily.com",
    "category": "articles",
    "source": "api_article",
    "num_highlights": 2,
    "last_highlight_at": "2021-12-07T04:27:23.398160Z",
    "updated": "2021-12-07T04:27:23.410096Z",
    "cover_image_url": "https://readwise-assets.s3.amazonaws.com/static/images/article0.00998d930354.png",
    "highlights_url": "https://readwise.io/bookreview/12187883",
    "source_url": "https://focusonthefamily.com/marriage/when-you-and-your-spouse-cant-agree",
    "asin": null,
    "tags": []
}
```

The second time is this:
```
{
    "id": 11891644,
    "title": "When You and Your Spouse Can't Agree - Focus on the Family",
    "author": "focusonthefamily.com",
    "category": "articles",
    "source": "instapaper",
    "num_highlights": 0,
    "last_highlight_at": "2021-11-15T17:16:41Z",
    "updated": "2021-11-15T18:00:11.741586Z",
    "cover_image_url": "https://readwise-assets.s3.amazonaws.com/static/images/article4.6bc1851654a0.png",
    "highlights_url": "https://readwise.io/bookreview/11891644",
    "source_url": "https://www.focusonthefamily.com/marriage/when-you-and-your-spouse-cant-agree/",
    "asin": null,
    "tags": []
}
```

So the instapaper version is still hanging around for now (still may be cached).
More importantly, the second version of the article shows num_highlights: 0.

That means that `latestHighlights` is empty when we process this second instance of the article, but I think the code is written to assume all existing books have highlights (a very reasonable assumption).

I see that there is code that checks for empty highlights, but it only checks for missing highlights in the event that the page doesn't exist yet.  In the edge case that I have, the page already exists because of a duplicate article in Readwise.

I was able to get around this issue by adding the following code after getting the latest highlights but before preparing the latest highlights:

```
    // Filter out only latest highlights
    const latestHighlights = highlightsForBook.data.results.filter(
      (b) => new Date(b.updated) > new Date(logseq.settings['latestRetrieved'])
    );

// new code here
    if (latestHighlights.length == 0) {
      console.log("No highlights found for '" + b.title + "'");
      continue;
    }
// end of new code    

    // Prepare latest highlights for logeq insertion
    let latestHighlightsArr;
```

I'm not sure how you want to handle this situation.  For me, I'm fine with just skipping a book with no highlights.

I will open a PR with this change, but if you prefer to solve it a different way, that is fine.

**Comment by benjypng** [comment]
Thanks! I've done the merge!
Have also created a credits section and added your contribution!
Thanks again!
