### ISSUE TITLE
Can't open import window again after Readwise sync 

### ISSUE THREAD

**Issue by dom8509** [hkgnp/logseq-readwise-plugin#20]
After performing a Readwise import I can't open the Readwise Import window again until a restart of the Logseq app is performed.

**Comment by benjypng** [comment]
It looks like the sync is stuck.
When you click sync, the "Sync New Sources" button should become blue again.
Does it for yours?

**Comment by benjypng** [comment]
Hmm, could you try with v4.0.13?
I did some refactoring to try and catch this bug.

**Comment by dom8509** [comment]
Cool I think it's working now, I was able to sync all my Readwise data with the new version. Thanks for bugfixing!

**Comment by benjypng** [comment]
That's good to hear! 
Please re-open the ticket if you still face issues!
