### ISSUE TITLE
Book View not displaying

### ISSUE THREAD

**Issue by jlcolbert** [hkgnp/logseq-readwise-plugin#22]
When I use the `/Book renderer` command, nothing displays.

<img width="697" alt="image" src="https://user-images.githubusercontent.com/17013952/168402580-15949b81-0d9e-4937-a630-3f71c967545e.png">

<img width="603" alt="image" src="https://user-images.githubusercontent.com/17013952/168402597-9d21ccd1-2a3d-41fb-a15f-84f2d2f1014e.png">

I have the latest version of the both the plugin and Logseq.

**Comment by sidsarasvati** [comment]
having the same issue on latest plugin install

**Comment by benjypng** [comment]
Fixed in v4.0.11
