### ISSUE TITLE
Sync crash

### ISSUE THREAD

**Issue by jesper-bylund** [hkgnp/logseq-readwise-plugin#23]
My syncing no longer works. It just stops at some percentage.

I've tried downgrading to Logseq 0.6.5 because I say that in another issue. Same result though.

With 0.6.5 I get the following error in the console:
<img width="677" alt="Screenshot 2022-05-14 at 11 27 04" src="https://user-images.githubusercontent.com/186083/168420182-afc97be8-5950-445b-a3c0-d4a9e9425509.png">

Seems to always happen with the same book.

Didn't find a good way to debug, any tips on how to proceed?

**Comment by benjypng** [comment]
Which book is this if you don't mind me asking?

**Comment by jesper-bylund** [comment]
This is "The Open Society and it's enemies" by Karl Popper originally highlighted on Kindle. Tried to look at the highlights in Readwise to see if they contained anything odd like special characters or so. Couldn't find anything.

Tips on how to debug?

**Comment by benjypng** [comment]
Hmm, could you try with v4.0.13?
I did some refactoring to try and catch this bug.

**Comment by jesper-bylund** [comment]
Just tried it with v4.0.15
got the following error:
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'uuid')
    at onClick (Sync.tsx:224)`
    
Still looks like it's on 
    `Updating The Open Society and Its Enemies`

Anything I can do to help?

**Comment by benjypng** [comment]
Could you update to v4.0.16 and try again?
This time, can you open up the developer console and take a screenshot of what you see?

**Comment by jesper-bylund** [comment]
Here's v4.0.16, also expanded the errors

<img width="1354" alt="Screenshot 2022-05-18 at 16 14 01" src="https://user-images.githubusercontent.com/186083/169062834-e6f1a5f0-e66d-4c96-8d07-de8594f7063b.png">
<img width="1354" alt="Screenshot 2022-05-18 at 16 14 16" src="https://user-images.githubusercontent.com/186083/169062867-779e1a74-a4d5-4d5f-899c-45713dab98fe.png">

**Comment by benjypng** [comment]
Thanks for the screenshots! They were helpful.
Could you try with v4.0.17 and see what happens please?

**Comment by jesper-bylund** [comment]
Ofc!
v4.0.17 here
<img width="1515" alt="Screenshot 2022-05-19 at 15 51 51" src="https://user-images.githubusercontent.com/186083/169309903-baba69d3-1df5-433b-aa17-cd3865b00747.png">
<img width="1515" alt="Screenshot 2022-05-19 at 15 51 59" src="https://user-images.githubusercontent.com/186083/169309934-d6b26807-7a47-4d52-84d6-dabbad09d8f6.png">

**Comment by benjypng** [comment]
Hmm, the line the console points to does not seem to be pointing at the newer code.
Is there a way that you can uninstall the plugin, quit logseq, reinstall the plugin and try again?
Will be good to backup the last sync time so you don't end up having to sync duplicates.

**Comment by jesper-bylund** [comment]
Did as instructed.
Synced with no issues.
<img width="1445" alt="Screenshot 2022-05-19 at 20 58 30" src="https://user-images.githubusercontent.com/186083/169380611-5c455d93-93c9-4c55-af4c-afd57f5eb43c.png">

Thank you, but really strange.

**Comment by benjypng** [comment]
Yes it definitely is!
