### ISSUE TITLE
Error "Sync in progress initiated by different client"

### ISSUE THREAD

**Issue by rubenvillar** [hkgnp/logseq-readwise-plugin#26]
Hi,
when I try to sync I get "Sync in progress initiated by different client" error.

Recently, I've reset my Logseq cache. After that, the error started to appear.

I've tried to reset Readwise plugin but it didn't fix the error.

If I watch the developer console, an error is throwed

<img width="737" alt="image" src="https://user-images.githubusercontent.com/4112766/184862242-952f3c95-4c2c-4586-8b2b-c9ef3078768e.png">

**Comment by benjypng** [comment]
Hi,
Readwise has since released an official plugin. Do you want to try that
instead?

**Comment by rubenvillar** [comment]
Hi,
you are totally right. 

I'm using the official plugin. I though this was the official plugin repo. 

¡Sorry!
