### ISSUE TITLE
prefer date format

### ISSUE THREAD

**Issue by feigaoxyz** [hkgnp/logseq-readwise-plugin#5]
The plugin does not comply with prefer date format, i.e., all its dates are "MMM do, yyyy".

I'd wish to the plugin to honor the logseq prefer date format or have a config to set it up for itself.

**Comment by benjypng** [comment]
v3.0 in the marketplace now respects your preferred date format, BUT only if it has "yyyy", "dd" and "MM" (and not like "E").

Give it a go and let me know? It will not apply retrospectively to imported highlights though.

**Comment by feigaoxyz** [comment]
thanks! will check out.

**Comment by benjypng** [comment]
Closing this issue. Please re-open it if it's not working for some reason!
