### ISSUE TITLE
Retrieved timestamp creates references to hh:mm: pages

### ISSUE THREAD

**Issue by MattHulse** [hkgnp/logseq-readwise-plugin#6]
Each imported book contains a properties section including `retrieved:: `.
This has a link to the journal date for when the highlight was imported, but also a hh:mm timestamp.  This ends up creating odd pages in my graph like the following:

`1:15:`
`1:16:`
`1:17:`

The link to the date the items are imported is nice, and the time may be interesting in the context of the highlight (more interesting if it was the actual 24 hour time).  However it is not something I want to link to.  

Here is a sample header for an imported highlight:
```
retrieved:: [[Dec 28th, 2021]], 1:15:
              author:: [[Psychology Today]]
              category:: [[articles]]
              source:: [[reader]]
```

**Comment by benjypng** [comment]
Thanks for the feedback!

I don't recall creating it, so maybe something automated in the background.

Will check and get back!

**Comment by benjypng** [comment]
Hi! I've checked. For me, it follows 24h timestamp though.

But anyway, I've offered a manual option to remove it if you don't want it. You can just go to the settings and indicate:
```
retrievedTime: false
```
By default it is set to `true`.

Release 3.01: https://github.com/hkgnp/logseq-readwise-plugin/releases/tag/v3.01

Hope this helps!
