### ISSUE TITLE
Twitter threads are ordered in the wrong order inside highlights

### ISSUE THREAD

**Issue by silver-vlas** [hkgnp/logseq-readwise-plugin#7]
When syncing a thread, In the readwise highlights section, the threads are synced in the reverse order, which means it's basically unreadable. 

The linked reference that appears in the Journal daily page, has sorting which is even weirder, it does not seem to follow any kind of logical pattern of sorting. 

Example in the linked image. 

![image](https://user-images.githubusercontent.com/55911890/147648665-a8f7e9a3-0601-4f15-a0a6-086042cc8d61.png)

**Comment by benjypng** [comment]
Thanks for highlighting this!

Can I check if you are sorting the highlights by recent first or recent last?

**Comment by silver-vlas** [comment]
Where would this setting be? I have not changed anything from the default neither in Readwise nor in the plugin.

**Comment by benjypng** [comment]
Hmm, which version are you on currently?

**Comment by silver-vlas** [comment]
Logseq Version: 0.5.5
Plugin Version: 3.01

**Comment by silver-vlas** [comment]
Ok - this is my pluging json settings content:

{
  "disabled": false,
  "sortRecentFirst": true,
  "latestRetrieved": "2021-12-29T08:26:13.115593Z",
  "token": "kXXKaFJuDZbkP1w4H5KCjJCHLURDSFhlwUFjgOt02WXCvhwtLf",
  "retrievedTime": true
}

**Comment by benjypng** [comment]
Hey! I deleted your comment as you included your API token！

I'll look into it and update you.

**Comment by benjypng** [comment]
Can you uncheck the checkbox "Sort recent highlights first"? Then the recent tweets will be at the bottom.

<img width="495" alt="Screenshot 2021-12-29 at 7 55 02 PM" src="https://user-images.githubusercontent.com/47936793/147659706-12d4c3dc-8f2b-4630-864c-18605eb5c0d5.png">

I also noticed that your "Readwise Highlights" header keeps getting recreated. Do you typically change it after you import a source, e.g. change from h2 to regular size? If you do so, the header "Readwise Highlights" will keep getting repeated.

**Comment by silver-vlas** [comment]
Yes, that works in the highlights page. Thank you.
But the Linked Reference page in the Journal is still not properly sorted from what I see.

**Comment by silver-vlas** [comment]
For Example:
![image](https://user-images.githubusercontent.com/55911890/147661168-fa5485b2-7961-4e0e-9cad-0946e2545f56.png)

**Comment by benjypng** [comment]
Hmm I am not sure how Linked References are sorted though. It's not controlled by the plugin as far as I know.

**Comment by silver-vlas** [comment]
I think perhaps that having the date as a property in every sub-block under "on" may be confusing logseq. 

In roam, I had configured Readwise to add the date on the [[Readwise Highlights]] row as a header to the entire paragraph and thus the linked reference would be a single one for the entire thread.

**Comment by benjypng** [comment]
Thanks for the suggestion! Will see if I can add this feature request for a future update!
