### ISSUE TITLE
Properties display and function

### ISSUE THREAD

**Issue by rosslaird** [hkgnp/logseq-readwise-plugin#8]
Great plugin; thanks so much for creating it.
I'm having a couple of small issues with properties: the content of the properties bullet is invisible when it is not active, and changing the order of the properties lines deletes content. Here are two screenshots that show the properties bullet when active and not active:
<img width="499" alt="Screen Shot 2022-01-15 at 9 23 59 AM" src="https://user-images.githubusercontent.com/75513/149631535-b2ce86f3-a365-40d4-9ef3-ba2b395edb22.png">
<img width="606" alt="Screen Shot 2022-01-15 at 12 57 18 PM" src="https://user-images.githubusercontent.com/75513/149637466-8bf10eb8-145b-4b48-96b5-7b77dcaf63eb.png">

With other properties bullets in Logseq, the properties bullet has a background and the properties are shown in bold. I've shown this default situation below, in case I am not describing it well:
<img width="573" alt="Screen Shot 2022-01-15 at 12 58 27 PM" src="https://user-images.githubusercontent.com/75513/149637507-5c05dfa2-d3af-42b8-bee6-874036e988ac.png">

So, there is something different about these Readwise properties that is preventing the background and bold effects and also making the bullet appear empty when it is not.
(In the first screenshot above I have removed the 14 spaces that the plugin inserts, for some reason, to each property line. I prefer the properties to be left-aligned. This change seems to make no difference to the issue I'm seeing. Also, if I move a property such as tags to the top of the list, that property is deleted when I click out of the bullet. I don't mind the order of the properties as it is; I just thought I would experiment with placing the tags at the top, to see if doing so would fix the issue, and that's when I noticed the deletion.)

**Comment by rosslaird** [comment]
Here is the page data for the page above ("The Robots of Dawn") where I am seeing this issue:

`{:db/id 907,
 :block/created-at 1642266207145,
 :block/file {:db/id 916},
 :block/journal? false,
 :block/name "the robots of dawn (readwise)",
 :block/original-name "The Robots of Dawn (Readwise)",
 :block/updated-at 1642268441207,
 :block/uuid #uuid "61e2fe5e-9cca-44f3-b476-d0e54b0cdad7"}
`

Note that it does not show a `:block/properties` entry, unlike the correctly-rendering page ("The Ship") shown in the screenshot above:

`{:block/alias [{:db/id 655}],
 :block/uuid #uuid "61e0e0de-1e61-4a17-b8a3-d1c19af040bc",
 :block/properties {:alias #{"ship"}, :tags #{"Ancients"}},
 :block/journal? false,
 :block/updated-at 1642268301696,
 :block/created-at 1642118004228,
 :block/tags [{:db/id 239}],
 :db/id 173,
 :block/name "the ship",
 :block/file {:db/id 94}, 
 :block/original-name "The Ship"}`

**Comment by benjypng** [comment]
Hey Ross, I cannot seem to be able to replicate the issue. Please see the video below.
Does this happen to all Readwise book highlights or just this one?

https://user-images.githubusercontent.com/47936793/149684628-01ab82f7-a4af-4fe5-84fc-477d3f493b19.mov

**Comment by rosslaird** [comment]
Thanks for looking into this. The issue appears with every Readwise highlight:

https://www.loom.com/share/fbc235ef8feb47308f7700bf9adb282c

**Comment by rosslaird** [comment]
Also, none of the properties (for author, category, source, tags) are created in my graph when these references are imported. And, as expected, when I create them manually, links to these references do not appear on those pages. So, for example, the page [[books]] remains empty after I have created it.

**Comment by benjypng** [comment]
> Thanks for looking into this. The issue appears with every Readwise highlight:
> 
> https://www.loom.com/share/fbc235ef8feb47308f7700bf9adb282c

Thanks for the video. I think this should be fixed in v3.7 in the marketplace. Do you mind giving it a try? Apologies did it in a hurry and it's a Monday so unable to extensively test it. This will not fix past highlights already brought in but only those new sources moving forward.

**Comment by benjypng** [comment]
> Also, none of the properties (for author, category, source, tags) are created in my graph when these references are imported. And, as expected, when I create them manually, links to these references do not appear on those pages. So, for example, the page [[books]] remains empty after I have created it.

Sorry I am not sure what this means. It will be empty but you can refer to the linked references to highlights from books brought in.

<img width="663" alt="Screenshot 2022-01-17 at 4 00 23 PM" src="https://user-images.githubusercontent.com/47936793/149701611-f26b7da6-a58d-4b10-8111-f347459a98e2.png">

**Comment by rosslaird** [comment]
Yes! Properties are displaying properly now, and linked references are being created as intended. What I meant about the properties not creating pages (above) is that the linked references were not being created (so, there were no linked references on the [[books]] page, for example). But this is working now.

There may still be a few issues with sync. Initially, the plugin imported a bunch of references I had deleted in Readwise, and with the latest update it missed the most recent reference — but found it on a subsequent refresh. I suppose this may not be related to the plugin itself but to Readwise's cache.

Thanks for your quick attention to this.

**Comment by benjypng** [comment]
No probs!
